// Autogenerated by geninfo.sh, do not edit

package gcewing.sg;

public class Info {
	static final String modName = "Delat SGCraft";
	static final String modID = "SGCraft";
	static final String modPackage = "sg";
	static final String versionNumber = "1.0.0";
	static final String versionBounds = "[0.1,0.7)";
}
