// Autogenerated by geninfo.sh, do not edit

package gcewing.sg;

public class Info {
	static final String modName = "Neo's SGCraft-Reloaded";
	static final String modID = "SGCraft";
	static final String modPackage = "sg";
	static final String versionNumber = "0.1.0";
	static final String versionBounds = "[0.1,0.7)";
}
