#!/usr/bin/env python3
"""Export the static assembled Stargate geometry for BlueMap.

This intentionally mirrors StargateBaseRenderer's shell, glyph-ring, and idle
chevron geometry. The animated event horizon, kawoosh, and iris are omitted.
"""

from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = (
    ROOT / "compat" / "bluemap" / "lanteacraft-stargates" / "assets" / "lanteacraft" / "models" / "obj",
    ROOT / "src" / "main" / "resources" / "assets" / "lanteacraft" / "models" / "obj",
)

RING_SEGMENTS = 38
INNER_RADIUS = 2.75
INNER_MOVING_RADIUS = INNER_RADIUS + 0.15
OUTER_RADIUS = 3.5
MID_RADIUS = INNER_MOVING_RADIUS + (OUTER_RADIUS - INNER_MOVING_RADIUS) / 2.0
RING_DEPTH = 0.15
CHEVRONS = 9
CHEVRON_OUTER_RADIUS = OUTER_RADIUS + 1.0 / 16.0
CHEVRON_WIDTH = 0.5
CHEVRON_DEPTH = 0.0625
CHEVRON_ANGLE = 360.0 / CHEVRONS
CHEVRON_ANGLE_OFFSET = -90.0 + CHEVRON_WIDTH

OUTER_TEXTURE = 0x04
FACE_TEXTURE = 0x14
INNER_TEXTURE = 0x17
CHEVRON_TEXTURE = 0x05
CHEVRON_LIT_TEXTURE = 0x16


class ObjWriter:
    def __init__(self) -> None:
        self.lines = [
            "# Generated by tools/export_stargate_obj.py",
            "# Static geometry mirrored from StargateBaseRenderer",
            "mtllib stargate_assembled.mtl",
            "o assembled_stargate",
        ]
        self.vertex_count = 0
        self.uv_count = 0
        self.normal_count = 0
        self.material = None

    @staticmethod
    def north_position(point: tuple[float, float, float]) -> tuple[float, float, float]:
        """Apply the renderer's base offset and its north-facing Y rotation."""
        x, y, z = point
        return 0.5 - x, 3.5 + y, 0.5 - z

    def quad(
        self,
        material: str,
        points: list[tuple[float, float, float]],
        uvs: list[tuple[float, float]],
    ) -> None:
        if self.material != material:
            self.lines.append(f"usemtl {material}")
            self.material = material

        transformed = [self.north_position(point) for point in points]
        for x, y, z in transformed:
            self.lines.append(f"v {x:.8f} {y:.8f} {z:.8f}")
        # OBJ uses a bottom-left texture origin. NeoForge's flip_v option turns
        # these back into the top-left UVs used by StargateBaseRenderer.
        for u, v in uvs:
            self.lines.append(f"vt {u:.8f} {1.0 - v:.8f}")

        a, b, c = transformed[:3]
        ab = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
        ac = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
        normal = (
            ab[1] * ac[2] - ab[2] * ac[1],
            ab[2] * ac[0] - ab[0] * ac[2],
            ab[0] * ac[1] - ab[1] * ac[0],
        )
        length = math.sqrt(sum(component * component for component in normal)) or 1.0
        normal = tuple(component / length for component in normal)
        self.lines.append(f"vn {normal[0]:.8f} {normal[1]:.8f} {normal[2]:.8f}")

        vi = self.vertex_count + 1
        ti = self.uv_count + 1
        ni = self.normal_count + 1
        self.lines.append("f " + " ".join(f"{vi+i}/{ti+i}/{ni}" for i in range(4)))
        self.vertex_count += 4
        self.uv_count += 4
        self.normal_count += 1

    def write(self, path: Path) -> None:
        path.write_text("\n".join(self.lines) + "\n", encoding="utf-8", newline="\n")


def tile_uv(tile: int, u: float, v: float) -> tuple[float, float]:
    return ((tile & 0xF) + u / 16.0) / 16.0, (((tile >> 4) & 0xF) + v / 16.0) / 16.0


def frame_quad(
    writer: ObjWriter,
    material: str,
    tile: int,
    vertices: list[tuple[float, float, float, float, float]],
) -> None:
    writer.quad(
        material,
        [(x, y, z) for x, y, z, _u, _v in vertices],
        [tile_uv(tile, u, v) for _x, _y, _z, u, v in vertices],
    )


def export_shell(writer: ObjWriter) -> None:
    bevel_depth = RING_DEPTH - 1.0 / 16.0
    sin = [math.sin(2.0 * math.pi * i / RING_SEGMENTS) for i in range(RING_SEGMENTS + 1)]
    cos = [math.cos(2.0 * math.pi * i / RING_SEGMENTS) for i in range(RING_SEGMENTS + 1)]

    for i in range(RING_SEGMENTS):
        c0, c1, s0, s1 = cos[i], cos[i + 1], sin[i], sin[i + 1]
        frame_quad(writer, "frame_85", OUTER_TEXTURE, [
            (OUTER_RADIUS*c0, OUTER_RADIUS*s0, RING_DEPTH, 0, 0),
            (OUTER_RADIUS*c0, OUTER_RADIUS*s0, -RING_DEPTH, 0, 1),
            (OUTER_RADIUS*c1, OUTER_RADIUS*s1, -RING_DEPTH, 1, 1),
            (OUTER_RADIUS*c1, OUTER_RADIUS*s1, RING_DEPTH, 1, 0),
        ])
        frame_quad(writer, "frame_75", INNER_TEXTURE, [
            (INNER_RADIUS*c0, INNER_RADIUS*s0, bevel_depth, 0, 0),
            (INNER_RADIUS*c1, INNER_RADIUS*s1, bevel_depth, 1, 0),
            (INNER_RADIUS*c1, INNER_RADIUS*s1, -bevel_depth, 1, 1),
            (INNER_RADIUS*c0, INNER_RADIUS*s0, -bevel_depth, 0, 1),
        ])
        frame_quad(writer, "frame_85", FACE_TEXTURE, [
            (MID_RADIUS*c0, MID_RADIUS*s0, RING_DEPTH, 0, 0),
            (MID_RADIUS*c1, MID_RADIUS*s1, RING_DEPTH, 16, 0),
            (MID_RADIUS*c1, MID_RADIUS*s1, -RING_DEPTH, 16, 16),
            (MID_RADIUS*c0, MID_RADIUS*s0, -RING_DEPTH, 0, 16),
        ])
        frame_quad(writer, "frame_85", FACE_TEXTURE, [
            (INNER_MOVING_RADIUS*c0, INNER_MOVING_RADIUS*s0, RING_DEPTH, 0, 0),
            (INNER_MOVING_RADIUS*c0, INNER_MOVING_RADIUS*s0, -RING_DEPTH, 0, 16),
            (INNER_MOVING_RADIUS*c1, INNER_MOVING_RADIUS*s1, -RING_DEPTH, 16, 16),
            (INNER_MOVING_RADIUS*c1, INNER_MOVING_RADIUS*s1, RING_DEPTH, 16, 0),
        ])
        frame_quad(writer, "frame", FACE_TEXTURE, [
            (MID_RADIUS*c0, MID_RADIUS*s0, RING_DEPTH, 16, 16),
            (OUTER_RADIUS*c0, OUTER_RADIUS*s0, RING_DEPTH, 16, 0),
            (OUTER_RADIUS*c1, OUTER_RADIUS*s1, RING_DEPTH, 0, 0),
            (MID_RADIUS*c1, MID_RADIUS*s1, RING_DEPTH, 0, 16),
        ])
        frame_quad(writer, "frame", FACE_TEXTURE, [
            (INNER_RADIUS*c0, INNER_RADIUS*s0, bevel_depth, 16, 16),
            (INNER_MOVING_RADIUS*c0, INNER_MOVING_RADIUS*s0, RING_DEPTH, 16, 0),
            (INNER_MOVING_RADIUS*c1, INNER_MOVING_RADIUS*s1, RING_DEPTH, 0, 0),
            (INNER_RADIUS*c1, INNER_RADIUS*s1, bevel_depth, 0, 16),
        ])
        frame_quad(writer, "frame_55", FACE_TEXTURE, [
            (INNER_RADIUS*c0, INNER_RADIUS*s0, -bevel_depth, 0, 16),
            (INNER_RADIUS*c1, INNER_RADIUS*s1, -bevel_depth, 16, 16),
            (INNER_MOVING_RADIUS*c1, INNER_MOVING_RADIUS*s1, -RING_DEPTH, 16, 0),
            (INNER_MOVING_RADIUS*c0, INNER_MOVING_RADIUS*s0, -RING_DEPTH, 0, 0),
        ])
        frame_quad(writer, "frame_55", FACE_TEXTURE, [
            (INNER_MOVING_RADIUS*c0, INNER_MOVING_RADIUS*s0, -RING_DEPTH, 0, 16),
            (INNER_MOVING_RADIUS*c1, INNER_MOVING_RADIUS*s1, -RING_DEPTH, 16, 16),
            (OUTER_RADIUS*c1, OUTER_RADIUS*s1, -RING_DEPTH, 16, 0),
            (OUTER_RADIUS*c0, OUTER_RADIUS*s0, -RING_DEPTH, 0, 0),
        ])

    inner = INNER_MOVING_RADIUS - 1.0 / 128.0
    outer = MID_RADIUS + 1.0 / 128.0
    z = RING_DEPTH - 1.0 / 64.0
    for i in range(RING_SEGMENTS):
        writer.quad("glyphs", [
            (inner*cos[i], inner*sin[i], z),
            (outer*cos[i], outer*sin[i], z),
            (outer*cos[i+1], outer*sin[i+1], z),
            (inner*cos[i+1], inner*sin[i+1], z),
        ], [
            ((i + 1) / RING_SEGMENTS, 0.66),
            ((i + 1) / RING_SEGMENTS, 0.0),
            (i / RING_SEGMENTS, 0.0),
            (i / RING_SEGMENTS, 0.66),
        ])


def rotate_z(point: tuple[float, float, float], degrees: float) -> tuple[float, float, float]:
    x, y, z = point
    angle = math.radians(degrees)
    return x * math.cos(angle) - y * math.sin(angle), x * math.sin(angle) + y * math.cos(angle), z


def export_chevrons(writer: ObjWriter) -> None:
    r1 = MID_RADIUS - 1.0 / 18.0
    r2 = CHEVRON_OUTER_RADIUS
    z_front = RING_DEPTH + CHEVRON_DEPTH
    x1, x2 = r1, r2
    y1, y2 = CHEVRON_WIDTH / 4.0, CHEVRON_WIDTH / 2.0
    inset = CHEVRON_WIDTH / 6.0
    lit_z = z_front + 1.0 / 256.0

    quads = [
        ("frame", CHEVRON_TEXTURE, [(x2,y2,z_front,0,0), (x1,y1,z_front,0,16), (x1+inset,0,z_front,8,12), (x2,y2-inset,z_front,4,2)]),
        ("frame", CHEVRON_TEXTURE, [(x2,-y2+inset,z_front,12,2), (x1+inset,0,z_front,8,12), (x1,-y1,z_front,16,16), (x2,-y2,z_front,16,0)]),
        ("chevron_lit", CHEVRON_LIT_TEXTURE, [(x2,y2-inset,lit_z,0,4), (x1+inset,y1-inset,lit_z,4,16), (x1+inset,0,lit_z,8,16), (x2,0,lit_z,8,4)]),
        ("chevron_lit", CHEVRON_LIT_TEXTURE, [(x2,0,lit_z,8,4), (x1+inset,0,lit_z,8,16), (x1+inset,-y1+inset,lit_z,12,16), (x2,-y2+inset,lit_z,16,4)]),
    ]
    for i in range(CHEVRONS):
        angle = i * CHEVRON_ANGLE - CHEVRON_ANGLE_OFFSET
        for material, tile, vertices in quads:
            frame_quad(writer, material, tile, [(*rotate_z((x, y, z), angle), u, v) for x, y, z, u, v in vertices])


def main() -> None:
    writer = ObjWriter()
    export_shell(writer)
    export_chevrons(writer)
    source_mtl = OUTPUTS[0] / "stargate_assembled.mtl"
    for output in OUTPUTS:
        output.mkdir(parents=True, exist_ok=True)
        writer.write(output / "stargate_assembled.obj")
        if output != OUTPUTS[0]:
            (output / "stargate_assembled.mtl").write_bytes(source_mtl.read_bytes())
        print(f"Wrote {writer.vertex_count // 4} quads to {output / 'stargate_assembled.obj'}")


if __name__ == "__main__":
    main()
